name: Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Testing
        run: |
          npm install
          npm test
        env:
          CI: true
          NODE_ENV: test
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
